// Auto-generated from rosy.pest by build.rs — do not edit!
// Regenerate with: cargo build -p rosy

/// @ts-nocheck
module.exports = grammar({
  name: 'rosy',

  extras: $ => [
    /\s/,
    $.comment,
  ],

  word: $ => $.identifier,

  rules: {
    source_file: $ => repeat($._item),

    _item: $ => choice(
      $.keyword,
      $.builtin_function,
      $.type_name,
      $.boolean,
      $.number,
      $.string,
      $.operator,
      $.punctuation,
      $.identifier,
    ),

    comment: $ => seq(
      '{',
      repeat(choice(
        $.comment,
        /[^{}]+/,
      )),
      '}',
    ),

    keyword: _ => token(prec(2, choice(
      seq(/[aA]/, /[rR]/, /[gG]/, /[gG]/, /[eE]/, /[tT]/),
      seq(/[bB]/, /[eE]/, /[gG]/, /[iI]/, /[nN]/),
      seq(/[bB]/, /[rR]/, /[eE]/, /[aA]/, /[kK]/),
      seq(/[cC]/, /[lL]/, /[oO]/, /[sS]/, /[eE]/, /[fF]/),
      seq(/[cC]/, /[pP]/, /[uU]/, /[sS]/, /[eE]/, /[cC]/),
      seq(/[dD]/, /[aA]/, /[cC]/, /[lL]/, /[iI]/, /[wW]/),
      seq(/[dD]/, /[aA]/, /[cC]/, /[qQ]/, /[lL]/, /[cC]/),
      seq(/[dD]/, /[aA]/, /[dD]/, /[eE]/, /[rR]/),
      seq(/[dD]/, /[aA]/, /[dD]/, /[iI]/, /[uU]/),
      seq(/[dD]/, /[aA]/, /[dD]/, /[mM]/, /[uU]/),
      seq(/[dD]/, /[aA]/, /[eE]/, /[pP]/, /[sS]/),
      seq(/[dD]/, /[aA]/, /[eE]/, /[sS]/, /[tT]/),
      seq(/[dD]/, /[aA]/, /[iI]/, /[nN]/, /[iI]/),
      seq(/[dD]/, /[aA]/, /[iI]/, /[nN]/, /[tT]/),
      seq(/[dD]/, /[aA]/, /[nN]/, /[oO]/, /[rR]/, /[oO]/),
      seq(/[dD]/, /[aA]/, /[nN]/, /[oO]/, /[rR]/, /[sS]/),
      seq(/[dD]/, /[aA]/, /[nN]/, /[oO]/, /[tT]/),
      seq(/[dD]/, /[aA]/, /[pP]/, /[eE]/, /[aA]/),
      seq(/[dD]/, /[aA]/, /[pP]/, /[eE]/, /[eE]/),
      seq(/[dD]/, /[aA]/, /[pP]/, /[eE]/, /[pP]/),
      seq(/[dD]/, /[aA]/, /[pP]/, /[eE]/, /[wW]/),
      seq(/[dD]/, /[aA]/, /[pP]/, /[lL]/, /[uU]/),
      seq(/[dD]/, /[aA]/, /[pP]/, /[rR]/, /[vV]/),
      seq(/[dD]/, /[aA]/, /[rR]/, /[eE]/, /[aA]/),
      seq(/[dD]/, /[aA]/, /[rR]/, /[eE]/, /[vV]/),
      seq(/[dD]/, /[aA]/, /[sS]/, /[cC]/, /[lL]/),
      seq(/[dD]/, /[aA]/, /[sS]/, /[gG]/, /[nN]/),
      seq(/[dD]/, /[aA]/, /[tT]/, /[rR]/, /[nN]/),
      seq(/[eE]/, /[lL]/, /[sS]/, /[eE]/),
      seq(/[eE]/, /[lL]/, /[sS]/, /[eE]/, /[iI]/, /[fF]/),
      seq(/[eE]/, /[nN]/, /[dD]/),
      seq(/[eE]/, /[nN]/, /[dD]/, /[fF]/, /[iI]/, /[tT]/),
      seq(/[eE]/, /[nN]/, /[dD]/, /[fF]/, /[uU]/, /[nN]/, /[cC]/, /[tT]/, /[iI]/, /[oO]/, /[nN]/),
      seq(/[eE]/, /[nN]/, /[dD]/, /[iI]/, /[fF]/),
      seq(/[eE]/, /[nN]/, /[dD]/, /[lL]/, /[oO]/, /[oO]/, /[pP]/),
      seq(/[eE]/, /[nN]/, /[dD]/, /[pP]/, /[lL]/, /[oO]/, /[oO]/, /[pP]/),
      seq(/[eE]/, /[nN]/, /[dD]/, /[pP]/, /[rR]/, /[oO]/, /[cC]/, /[eE]/, /[dD]/, /[uU]/, /[rR]/, /[eE]/),
      seq(/[eE]/, /[nN]/, /[dD]/, /[wW]/, /[hH]/, /[iI]/, /[lL]/, /[eE]/),
      seq(/[fF]/, /[iI]/, /[tT]/),
      seq(/[fF]/, /[uU]/, /[nN]/, /[cC]/, /[tT]/, /[iI]/, /[oO]/, /[nN]/),
      seq(/[iI]/, /[fF]/),
      seq(/[iI]/, /[mM]/, /[uU]/, /[nN]/, /[iI]/, /[tT]/),
      seq(/[lL]/, /[dD]/, /[eE]/, /[tT]/),
      seq(/[lL]/, /[eE]/, /[vV]/),
      seq(/[lL]/, /[iI]/, /[nN]/, /[vV]/),
      seq(/[lL]/, /[oO]/, /[oO]/, /[pP]/),
      seq(/[lL]/, /[sS]/, /[lL]/, /[iI]/, /[nN]/, /[eE]/),
      seq(/[mM]/, /[bB]/, /[lL]/, /[oO]/, /[cC]/, /[kK]/),
      seq(/[mM]/, /[eE]/, /[mM]/, /[dD]/, /[pP]/, /[vV]/),
      seq(/[mM]/, /[eE]/, /[mM]/, /[fF]/, /[rR]/, /[eE]/),
      seq(/[mM]/, /[tT]/, /[rR]/, /[eE]/, /[eE]/),
      seq(/[oO]/, /[pP]/, /[eE]/, /[nN]/, /[fF]/),
      seq(/[oO]/, /[pP]/, /[eE]/, /[nN]/, /[fF]/, /[bB]/),
      seq(/[oO]/, /[sS]/),
      seq(/[pP]/, /[lL]/, /[oO]/, /[oO]/, /[pP]/),
      seq(/[pP]/, /[nN]/, /[pP]/, /[rR]/, /[oO]/),
      seq(/[pP]/, /[oO]/, /[lL]/, /[vV]/, /[aA]/, /[lL]/),
      seq(/[pP]/, /[rR]/, /[oO]/, /[cC]/, /[eE]/, /[dD]/, /[uU]/, /[rR]/, /[eE]/),
      seq(/[pP]/, /[wW]/, /[tT]/, /[iI]/, /[mM]/, /[eE]/),
      seq(/[qQ]/, /[uU]/, /[iI]/, /[tT]/),
      seq(/[rR]/, /[eE]/, /[aA]/, /[dD]/),
      seq(/[rR]/, /[eE]/, /[aA]/, /[dD]/, /[bB]/),
      seq(/[rR]/, /[eE]/, /[aA]/, /[dD]/, /[mM]/),
      seq(/[rR]/, /[eE]/, /[cC]/, /[sS]/, /[tT]/),
      seq(/[rR]/, /[eE]/, /[rR]/, /[aA]/, /[nN]/),
      seq(/[rR]/, /[kK]/, /[cC]/, /[oO]/),
      seq(/[sS]/, /[cC]/, /[rR]/, /[lL]/, /[eE]/, /[nN]/),
      seq(/[sS]/, /[lL]/, /[eE]/, /[eE]/, /[pP]/, /[mM]/),
      seq(/[sS]/, /[tT]/, /[cC]/, /[rR]/, /[eE]/),
      seq(/[sS]/, /[uU]/, /[bB]/, /[sS]/, /[tT]/, /[rR]/),
      seq(/[vV]/, /[aA]/, /[rR]/, /[iI]/, /[aA]/, /[bB]/, /[lL]/, /[eE]/),
      seq(/[vV]/, /[eE]/, /[dD]/, /[oO]/, /[tT]/),
      seq(/[vV]/, /[eE]/, /[lL]/, /[gG]/, /[eE]/, /[tT]/),
      seq(/[vV]/, /[eE]/, /[lL]/, /[sS]/, /[eE]/, /[tT]/),
      seq(/[vV]/, /[eE]/, /[uU]/, /[nN]/, /[iI]/, /[tT]/),
      seq(/[vV]/, /[eE]/, /[zZ]/, /[eE]/, /[rR]/, /[oO]/),
      seq(/[wW]/, /[hH]/, /[iI]/, /[lL]/, /[eE]/),
      seq(/[wW]/, /[rR]/, /[iI]/, /[tT]/, /[eE]/),
      seq(/[wW]/, /[rR]/, /[iI]/, /[tT]/, /[eE]/, /[bB]/),
      seq(/[wW]/, /[rR]/, /[iI]/, /[tT]/, /[eE]/, /[mM]/)
    ))),

    builtin_function: _ => token(prec(2, choice(
      seq(/[aA]/, /[bB]/, /[sS]/),
      seq(/[aA]/, /[cC]/, /[oO]/, /[sS]/),
      seq(/[aA]/, /[sS]/, /[iI]/, /[nN]/),
      seq(/[aA]/, /[tT]/, /[aA]/, /[nN]/),
      seq(/[cC]/, /[dD]/),
      seq(/[cC]/, /[mM]/),
      seq(/[cC]/, /[mM]/, /[pP]/, /[lL]/, /[xX]/),
      seq(/[cC]/, /[oO]/, /[nN]/, /[jJ]/),
      seq(/[cC]/, /[oO]/, /[nN]/, /[sS]/),
      seq(/[cC]/, /[oO]/, /[sS]/),
      seq(/[cC]/, /[oO]/, /[sS]/, /[hH]/),
      seq(/[dD]/, /[aA]/),
      seq(/[eE]/, /[rR]/, /[fF]/),
      seq(/[eE]/, /[xX]/, /[pP]/),
      seq(/[iI]/, /[mM]/, /[aA]/, /[gG]/),
      seq(/[iI]/, /[nN]/, /[tT]/),
      seq(/[iI]/, /[sS]/, /[rR]/, /[tT]/),
      seq(/[iI]/, /[sS]/, /[rR]/, /[tT]/, '3'),
      seq(/[lL]/, /[cC]/, /[dD]/),
      seq(/[lL]/, /[cC]/, /[mM]/),
      seq(/[lL]/, /[dD]/, /[aA]/),
      seq(/[lL]/, /[eE]/, /[nN]/, /[gG]/, /[tT]/, /[hH]/),
      seq(/[lL]/, /[lL]/, /[oO]/),
      seq(/[lL]/, /[oO]/),
      seq(/[lL]/, /[oO]/, /[gG]/),
      seq(/[lL]/, /[rR]/, /[eE]/),
      seq(/[lL]/, /[sS]/, /[tT]/),
      seq(/[lL]/, /[tT]/, /[rR]/, /[iI]/, /[mM]/),
      seq(/[lL]/, /[vV]/, /[eE]/),
      seq(/[nN]/, /[iI]/, /[nN]/, /[tT]/),
      seq(/[nN]/, /[oO]/, /[rR]/, /[mM]/),
      seq(/[rR]/, /[eE]/),
      seq(/[rR]/, /[eE]/, /[aA]/, /[lL]/),
      seq(/[sS]/, /[iI]/, /[nN]/),
      seq(/[sS]/, /[iI]/, /[nN]/, /[hH]/),
      seq(/[sS]/, /[qQ]/, /[rR]/),
      seq(/[sS]/, /[qQ]/, /[rR]/, /[tT]/),
      seq(/[sS]/, /[tT]/),
      seq(/[tT]/, /[aA]/, /[nN]/),
      seq(/[tT]/, /[aA]/, /[nN]/, /[hH]/),
      seq(/[tT]/, /[rR]/, /[iI]/, /[mM]/),
      seq(/[tT]/, /[yY]/, /[pP]/, /[eE]/),
      seq(/[vV]/, /[aA]/, /[rR]/, /[mM]/, /[eE]/, /[mM]/),
      seq(/[vV]/, /[aA]/, /[rR]/, /[pP]/, /[oO]/, /[iI]/),
      seq(/[vV]/, /[eE]/),
      seq(/[vV]/, /[mM]/, /[aA]/, /[xX]/),
      seq(/[vV]/, /[mM]/, /[iI]/, /[nN]/),
      seq(/[wW]/, /[eE]/, /[rR]/, /[fF]/)
    ))),

    type_name: _ => token(prec(2, choice(
      seq(/[rR]/, /[eE]/),
      seq(/[sS]/, /[tT]/),
      seq(/[lL]/, /[oO]/),
      seq(/[cC]/, /[mM]/),
      seq(/[vV]/, /[eE]/),
      seq(/[dD]/, /[aA]/),
      seq(/[cC]/, /[dD]/)
    ))),

    boolean: _ => token(prec(2, choice(
      seq(/[tT]/, /[rR]/, /[uU]/, /[eE]/),
      seq(/[fF]/, /[aA]/, /[lL]/, /[sS]/, /[eE]/)
    ))),

    number: _ => /\d+(\.\d+)?/,

    string: _ => choice(
      /"[^"]*"/,
      /'(?:''|[^'])*'/,
    ),

    operator: _ => choice(
      ':=', '==', '!=', '<>', '<=', '>=',
      '+', '-', '*', '/', '^', '%', '|', '&', '#',
      '=', '<', '>', '!',
    ),

    punctuation: _ => choice(';', '(', ')', '[', ']', ',', '.'),

    identifier: _ => /[a-zA-Z_][a-zA-Z0-9_]*/,
  },
});
